# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d84d17f85e751ee4b52928f670e08acf6125eebaf333b4af64127f2484173b506274e5698fe5e069e9ce215046357da9b0c358004fa63d023d6c6dd3a828b73d

test:
  secret_key_base: eafad80ca4237e385296196118708253189a40f32f22af0e244d15d354d3d139fd9967543f0259092299132bf6e76f9dffc7a53609b127144956dee179a64ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
